# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # secret_key_base: 549f270aa46c9b545cae6e82e916c7fbac20aa2eb99cf2ce44c4c571d1b2040fa38ae40d712e35212a46063ae8f7f21b9442fbcde6951ab899915358aea4a5a7
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


test:
  # secret_key_base: a6a27c5597787d98a4c0ee1f06b461a01e964dae66171e673e79807ffbf90a4db1e36dd5e0b4cc43cc9b3bcb643a62fbd6eee25471aeb1c1a6e2936b90aa9e52
  secret_key_base: ~~~~~~~~

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

